name: Continuous Integration
on: push # trigger for the workflow (here it is push event)
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      # - name: Run Linting   # commenting lint as project folder structure is not proper so lint would fail.
      #   run: |
      #     go fmt ./...
      #     go vet ./...
      # - name: Build          # commenting this as well as the folder structures are not proper
      #   run: go build *.go